# Main
FIELD_SIZE = 25
ENERGY_BONUS = 10
INITIAL_ENERGY = 20
MAX_ENERGY = 100
INITIAL_FOOD_NUM = 25
INITIAL_IND_NUM = 24
FOOD_LIVING_TIME = 10
IND_LIVING_TIME = 1000
FOOD_SPAWN_PROBABILITY = 0.1
FOOD_SPAWN_NUM = 25

# Actions
ALL_ACTIONS = ['L', 'LU', 'U', 'UR', 'R', 'RD', 'D', 'DL']

# Graphics
FPS = 10
SHOW = True
SHOW_NUMBERS = False

# Genetic algorithm
INDPB = 0.01
MU = 0
SIGMA = 0.1
ALPHA = 0.1
BEST_IND_NUM = 1
LOAD_NN = True

# Epochs
EPOCHS = 1